# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 07:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('V', 'V'), ('G', 'G')], max_length=1)),
            ],
            options={
                'ordering': ['number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[students.validators.validate_date])),
                ('topic', models.CharField(max_length=60, unique=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
            options={
                'ordering': ['date', 'subject', 'clazz'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject'),
        ),
    ]
