# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)])),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('V', 'V'), ('G', 'G')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ['number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[students.validators.validate_date])),
                ('topic', models.CharField(max_length=60, unique=True)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
            options={
                'ordering': ['date', 'subject', 'clazz'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('details', models.TextField(blank=True, max_length=256)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
            options={
                'ordering': ['-deadline', 'clazz', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('class_number', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('video_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-last_edited_on'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.URLField(default='http://elsyser.herokuapp.com/static/default.png')),
                ('info', models.TextField(blank=True, max_length=2048)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('title', 'content')]),
        ),
    ]
