# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2048)),
                ('date', models.DateField(auto_now=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
