# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['number', 'letter'], 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', 'title', 'clazz'], 'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='title',
            new_name='letter',
        ),
    ]
