# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20161103_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', 'title'], 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='clazz',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
    ]
