# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170801_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='student',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
