# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_news_clazz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='clazz',
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
