# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20161105_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-posted_on', 'title', 'clazz'], 'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='posted_on',
        ),
    ]
