# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20161105_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='./default.png', upload_to='images/'),
        ),
    ]
