# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20161106_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
