# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20161106_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
