# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
