# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20161107_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(validators=[students.validators.validate_date])),
                ('details', models.TextField(max_length=256)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject')),
            ],
            options={
                'ordering': ['-deadline', 'clazz', 'subject'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
