# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20161107_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='details',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
