# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20161108_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-posted_on', 'title'], 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='clazz',
        ),
    ]
