# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20161109_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
