# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20161109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
