# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20161110_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-posted_on', 'title'], 'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
