# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('news', 'content')]),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('title', 'content')]),
        ),
    ]
