# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_auto_20161112_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
