# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_auto_20161112_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([]),
        ),
    ]
