# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_auto_20161112_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('title', 'content')]),
        ),
    ]
