# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_auto_20161112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2048),
        ),
    ]
