# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_auto_20161113_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
