# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_auto_20161115_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
