# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_student_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-last_edited_on'], 'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
