# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_auto_20161224_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='details',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
