# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_auto_20161224_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='author',
        ),
    ]
