# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='class_number',
            field=models.IntegerField(choices=[(8, 8), (8, 8), (8, 8), (8, 8), (9, 9), (9, 9), (9, 9), (9, 9), (10, 10), (10, 10), (10, 10), (10, 10), (11, 11), (11, 11), (11, 11), (11, 11), (12, 12), (12, 12), (12, 12), (12, 12)], default=1),
            preserve_default=False,
        ),
    ]
