# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_material_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='class_number',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
    ]
