# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0053_auto_20161229_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='url',
        ),
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='section',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
