# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0054_auto_20161230_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
