# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_auto_20161230_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(),
        ),
    ]
