# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20161231_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(upload_to='/'),
        ),
    ]
