# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20161231_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='images/default.png', upload_to=students.models.get_upload_path),
        ),
    ]
