# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0060_submission_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solution_url',
            field=models.URLField(blank=True),
        ),
    ]
