# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0061_submission_solution_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
