# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_auto_20170106_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
