# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_auto_20170106_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Teacher'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Teacher'),
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Teacher'),
        ),
    ]
