# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_auto_20170106_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
