# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_auto_20170106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Teacher'),
        ),
    ]
