# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_grade'),
        ('news', '0002_auto_20170304_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='clazz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Class'),
            preserve_default=False,
        ),
    ]
