# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170602_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_image',
            field=models.URLField(blank=True),
        ),
    ]
