# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170807_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='author',
        ),
    ]
