# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170807_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='class_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
