# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 11:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170807_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='class_letter',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('V', 'V'), ('G', 'G')], max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='class_number',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=8, validators=[[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]]),
        ),
    ]
