# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('class_number', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('video_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject')),
            ],
        ),
    ]
