# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='class_number',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], validators=[[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]]),
        ),
    ]
