# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='_class',
            new_name='clazz',
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('V', 'V'), ('G', 'G')], max_length=1),
        ),
    ]
