# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20161019_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['number', 'title']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', 'subject', 'clazz']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.Teacher'),
        ),
    ]
