# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20161021_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title', 'teacher']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.CharField(default='Amplifiers', max_length=60),
            preserve_default=False,
        ),
    ]
