# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import exams.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20161022_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date', 'subject', 'clazz']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[exams.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
