# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_auto_20170919_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['deadline', 'clazz', 'subject']},
        ),
    ]
