# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20171118_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['num_vote_up', 'date']},
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateField(),
        ),
    ]
