# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20171118_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['vote_score', 'date']},
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='talk',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
