# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20171120_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='meetup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='talks.Meetup'),
        ),
    ]
