# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20171204_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['votes__count']},
        ),
        migrations.AddField(
            model_name='meetup',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
