# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_auto_20171205_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['vote_score']},
        ),
    ]
